In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('SummerProducts.csv')
df.head(4)

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.0,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.0,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.0,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   object
 1   title_orig                    1573 non-null   object
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   object
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   object
 19  product_color                 1532 non-null   object
 20  product_variation_size_id     1559 non-null   object
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   object
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    object
 29  origin_country                1556 non-null   object
 30  merchant_title                1573 non-null   object
 31  merchant_name                 1569 non-null   object
 32  merchant_info_subtitle        1572 non-null   object
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   object
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    object
 38  product_url                   1573 non-null   object
 39  product_picture               1573 non-null   object
 40  product_id                    1573 non-null   object
 41  theme                         1573 non-null   object
 42  crawl_month                   1573 non-null   object
dtypes: float64(9), int64(15), object(19)
memory usage: 528.6+ KB

In [4]:
df.isna().sum()

title                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                 45
rating_four_count                 45
rating_three_count                45
rating_two_count                  45
rating_one_count                  45
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                     41
product_variation_size_id         14
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
urgency_text                    1100
origin_country                    17
merchant_title                     0
merchant_name                      4
merchant_info_subtitle             1
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
merchant_profile_picture        1347
product_url                        0
product_picture                    0
product_id                         0
theme                              0
crawl_month                        0
dtype: int64

In [5]:
df['rating_count'].describe()

count     1573.000000
mean       889.659250
std       1983.928834
min          0.000000
25%         24.000000
50%        150.000000
75%        855.000000
max      20744.000000
Name: rating_count, dtype: float64

In [43]:
mask_rating = df['rating_count'] == 0
df[mask_rating]

Empty DataFrame
Columns: [product_id, merchant_id, merchant_title, merchant_rating_count, merchant_rating, title_orig, rating_count, rating, uses_ad_boosts, product_variation_inventory, merchant_has_profile_picture, badges_count, badge_local_product, badge_product_quality, badge_fast_shipping, tags, price, retail_price, units_sold, shipping_option_price, shipping_is_express, countries_shipped_to, origin_country, product_url, income, IncomeCat, coship_cat, MeRating_Cat, Rating_Cat, price_difference]
Index: []

[0 rows x 30 columns]

In [6]:
df['merchant_rating_count'].describe()

count    1.573000e+03
mean     2.649583e+04
std      7.847446e+04
min      0.000000e+00
25%      1.987000e+03
50%      7.936000e+03
75%      2.456400e+04
max      2.174765e+06
Name: merchant_rating_count, dtype: float64

In [7]:
df['price'].describe()

count    1573.000000
mean        8.325372
std         3.932030
min         1.000000
25%         5.810000
50%         8.000000
75%        11.000000
max        49.000000
Name: price, dtype: float64

In [8]:
df['rating'].describe()

count    1573.000000
mean        3.820896
std         0.515374
min         1.000000
25%         3.550000
50%         3.850000
75%         4.110000
max         5.000000
Name: rating, dtype: float64

In [9]:
percentile_25 = df['rating_count'].quantile(0.25)
percentile_25

24.0

In [10]:
df = df.drop(df[df['rating_count'] < percentile_25].index)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1184 entries, 0 to 1570
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1184 non-null   object
 1   title_orig                    1184 non-null   object
 2   price                         1184 non-null   float64
 3   retail_price                  1184 non-null   int64
 4   currency_buyer                1184 non-null   object
 5   units_sold                    1184 non-null   int64
 6   uses_ad_boosts                1184 non-null   int64
 7   rating                        1184 non-null   float64
 8   rating_count                  1184 non-null   int64
 9   rating_five_count             1184 non-null   float64
 10  rating_four_count             1184 non-null   float64
 11  rating_three_count            1184 non-null   float64
 12  rating_two_count              1184 non-null   float64
 13  rating_one_count              1184 non-null   float64
 14  badges_count                  1184 non-null   int64
 15  badge_local_product           1184 non-null   int64
 16  badge_product_quality         1184 non-null   int64
 17  badge_fast_shipping           1184 non-null   int64
 18  tags                          1184 non-null   object
 19  product_color                 1151 non-null   object
 20  product_variation_size_id     1171 non-null   object
 21  product_variation_inventory   1184 non-null   int64
 22  shipping_option_name          1184 non-null   object
 23  shipping_option_price         1184 non-null   int64
 24  shipping_is_express           1184 non-null   int64
 25  countries_shipped_to          1184 non-null   int64
 26  inventory_total               1184 non-null   int64
 27  has_urgency_banner            354 non-null    float64
 28  urgency_text                  354 non-null    object
 29  origin_country                1169 non-null   object
 30  merchant_title                1184 non-null   object
 31  merchant_name                 1183 non-null   object
 32  merchant_info_subtitle        1184 non-null   object
 33  merchant_rating_count         1184 non-null   int64
 34  merchant_rating               1184 non-null   float64
 35  merchant_id                   1184 non-null   object
 36  merchant_has_profile_picture  1184 non-null   int64
 37  merchant_profile_picture      194 non-null    object
 38  product_url                   1184 non-null   object
 39  product_picture               1184 non-null   object
 40  product_id                    1184 non-null   object
 41  theme                         1184 non-null   object
 42  crawl_month                   1184 non-null   object
dtypes: float64(9), int64(15), object(19)
memory usage: 407.0+ KB

In [12]:
df['rating_count'].describe()

count     1184.000000
mean      1179.123311
std       2211.582871
min         24.000000
25%         94.000000
50%        426.000000
75%       1239.500000
max      20744.000000
Name: rating_count, dtype: float64

In [13]:
df = df[['product_id','merchant_id','merchant_title','merchant_rating_count','merchant_rating','title_orig','rating_count','rating','uses_ad_boosts','product_variation_inventory','merchant_has_profile_picture','badges_count','badge_local_product','badge_product_quality','badge_fast_shipping','tags','price','retail_price','units_sold','shipping_option_price','shipping_is_express','countries_shipped_to','origin_country','product_url']]
df.head(3)

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,badge_fast_shipping,tags,price,retail_price,units_sold,shipping_option_price,shipping_is_express,countries_shipped_to,origin_country,product_url
0,5e9ae51d43d6a96e303acdb0,595097d6a26f6e070cb878d1,zgrdejia,568,4.128521,2020 Summer Vintage Flamingo Print Pajamas Se...,54,3.76,0,50,...,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",16.0,14,100,4,0,34,CN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0
1,58940d436a0d3d5da4e95a38,56458aa03a698c35c9050988,SaraHouse,17752,3.899673,Women's Casual Summer Sleeveless Sexy Mini Dress,6135,3.45,1,50,...,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",8.0,22,20000,2,0,41,CN,https://www.wish.com/c/58940d436a0d3d5da4e95a38
3,5cedf17ad1d44c52c59e4aca,58cfdefdacb37b556efdff7c,allenfan,23832,4.020435,Hot Summer Cool T Shirt for Women Fashion Tops...,579,4.03,1,50,...,0,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",8.0,8,5000,2,0,41,CN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1184 entries, 0 to 1570
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   product_id                    1184 non-null   object
 1   merchant_id                   1184 non-null   object
 2   merchant_title                1184 non-null   object
 3   merchant_rating_count         1184 non-null   int64
 4   merchant_rating               1184 non-null   float64
 5   title_orig                    1184 non-null   object
 6   rating_count                  1184 non-null   int64
 7   rating                        1184 non-null   float64
 8   uses_ad_boosts                1184 non-null   int64
 9   product_variation_inventory   1184 non-null   int64
 10  merchant_has_profile_picture  1184 non-null   int64
 11  badges_count                  1184 non-null   int64
 12  badge_local_product           1184 non-null   int64
 13  badge_product_quality         1184 non-null   int64
 14  badge_fast_shipping           1184 non-null   int64
 15  tags                          1184 non-null   object
 16  price                         1184 non-null   float64
 17  retail_price                  1184 non-null   int64
 18  units_sold                    1184 non-null   int64
 19  shipping_option_price         1184 non-null   int64
 20  shipping_is_express           1184 non-null   int64
 21  countries_shipped_to          1184 non-null   int64
 22  origin_country                1169 non-null   object
 23  product_url                   1184 non-null   object
dtypes: float64(3), int64(14), object(7)
memory usage: 231.2+ KB

In [15]:
df.isna().sum()

product_id                       0
merchant_id                      0
merchant_title                   0
merchant_rating_count            0
merchant_rating                  0
title_orig                       0
rating_count                     0
rating                           0
uses_ad_boosts                   0
product_variation_inventory      0
merchant_has_profile_picture     0
badges_count                     0
badge_local_product              0
badge_product_quality            0
badge_fast_shipping              0
tags                             0
price                            0
retail_price                     0
units_sold                       0
shipping_option_price            0
shipping_is_express              0
countries_shipped_to             0
origin_country                  15
product_url                      0
dtype: int64

In [16]:
df['origin_country'].value_counts()

origin_country
CN    1141
US      25
SG       1
VE       1
GB       1
Name: count, dtype: int64

In [17]:
null_rows_e = df.loc[df['origin_country'].isnull()]
print(null_rows_e)

                    product_id               merchant_id     merchant_title  \
56    5e81acbde187530740f207c6  5268759b736046671957190c          Maryswill
180   5dde07c651fe4539f9c3ee70  5177b0b63feb620dd802a197            Maxnina
498   552f840fcea30816e52aabcf  52bd3ddb34067e4620a4c62d           freebird
507   5d8d8f2e0c400f2f97671e30  5268759b736046671957190c          Maryswill
547   56f640b461d6cf68cb5c5d83  542a670d4f66d92eba599455  BUSINESS INDUSTRY
802   5d82f19340367911da1b9ee7  5177b0b63feb620dd802a197            Maxnina
921   5dafd1e7e580730831a8a64c  5268759b736046671957190c          Maryswill
943   57ccc65975aea72c65411bc6  52bd3ddb34067e4620a4c62d           freebird
1059  5d3120c92435742c362a09ec  5177b0b63feb620dd802a197            Maxnina
1147  5d8d8f2e0c400f2f97671e30  5268759b736046671957190c          Maryswill
1229  5d82f19340367911da1b9ee7  5177b0b63feb620dd802a197            Maxnina
1244  5d806bcf77593b45bd7cff78  51aff6a38e221e2cafcdc0cb      Clothingloves
1256  5d3eba3f20e552131d7dcb40  5177b0b63feb620dd802a197            Maxnina
1289  5e81acbde187530740f207c6  5268759b736046671957190c          Maryswill
1296  5801bf9ef22bef78458987d8  52bd3ddb34067e4620a4c62d           freebird

      merchant_rating_count  merchant_rating  \
56                    91631         3.837937
180                  105015         3.789601
498                  839882         4.103760
507                   91631         3.837937
547                   32923         4.209155
802                  105015         3.789601
921                   91631         3.837937
943                  839882         4.103760
1059                 105015         3.789601
1147                  91631         3.837937
1229                 105015         3.789601
1244                  82219         3.590083
1256                 105015         3.789601
1289                  91631         3.837937
1296                 839882         4.103760

                                             title_orig  rating_count  rating  \
56    New Fashion Summer Women Casual Dress Round Ne...            52    3.56
180   Summer Women s  Fashion  Lace Up Tie Pants  Pl...            79    3.35
498   Fashion Women Back Deep V Sexy Backless Vest T...          9075    3.35
507   2019 New Fashion Women Loose Round Neck Dress ...            97    3.90
547   Women Two Piece Set Print Wave Striped Sleevel...          5781    3.41
802   New Summer Women's New Fashion Sleeveless Polk...            42    3.71
921   Plus Size Summer Women Casual Sleeveless Rompe...           639    3.99
943   Womens Sleeveless Strapless Tube Tops Bandeau ...          2090    3.78
1059  Plus Size Summer Women Casual Sleeveless Rompe...           128    3.73
1147  2019 New Fashion Women Loose Round Neck Dress ...            97    3.90
1229  New Summer Women's New Fashion Sleeveless Polk...            42    3.71
1244  Women Fashion Swimwear Two Pieces Split Bikini...           300    4.20
1256  New Fashion Women Loose Round Neck Dress Short...            30    3.60
1289  New Fashion Summer Women Casual Dress Round Ne...            52    3.56
1296  New Sexy Women Bandage Cut Out Tank Tops Ladie...          7242    3.63

      uses_ad_boosts  product_variation_inventory  ...  badge_fast_shipping  \
56                 0                            2  ...                    0
180                1                            1  ...                    0
498                1                           50  ...                    0
507                0                            2  ...                    0
547                0                           50  ...                    0
802                0                            1  ...                    0
921                0                           50  ...                    0
943                1                           50  ...                    0
1059               1                           50  ...                    0
1147               0                            2  ...                    0
1229               0                            1  ...                    0
1244               0                           30  ...                    0
1256               0                           50  ...                    0
1289               0                            2  ...                    0
1296               0                           50  ...                    0

                                                   tags  price  retail_price  \
56    Summer,Fashion,Necks,Beach,Dress,Loose,beach d...   1.00            10
180   Summer,Shorts,high waist shorts,high waist,Cas...   3.78             4
498   Vest,womens top,Tank,Tops,slim,T Shirts,Womens...   7.00            13
507   Summer,Fashion,Necks,Sleeve,Dress,neck dress,s...   1.85            11
547   chiffon dress,strapdres,Dress,summer dress,bac...   8.00             7
802   Summer,Fashion,Mini,Tops,Polkas,V-neck,Casual,...   3.68             4
921   Deep V-Neck,Summer,Plus Size,Spaghetti Strap,O...   5.83             8
943   Summer,strapless,Tank,Tops,Women's Fashion,tan...   9.00            26
1059  Deep V-Neck,Summer,Plus Size,Spaghetti Strap,O...  11.00            10
1147  Summer,Fashion,Necks,Sleeve,Dress,neck dress,s...   1.85            11
1229  Summer,Fashion,Mini,Tops,Polkas,V-neck,Casual,...   3.68             4
1244  Summer,sexy bathing suit,Bikinis Set,splitbiki...   9.00             9
1256  Summer,Fashion,Necks,Sleeve,Dress,neck dress,s...  12.00            11
1289  Summer,Fashion,Necks,Beach,Dress,Loose,beach d...   1.00            10
1296  Summer,sportytankini,crop top,Tank,Tops,tank t...   5.67             5

      units_sold shipping_option_price  shipping_is_express  \
56           100                     1                    0
180         1000                     1                    0
498        50000                     2                    0
507          100                     1                    0
547        20000                     3                    0
802          100                     1                    0
921         5000                     2                    0
943        10000                     3                    0
1059        1000                     2                    0
1147         100                     1                    0
1229         100                     1                    0
1244        1000                     3                    0
1256         100                     3                    0
1289         100                     1                    0
1296       20000                     1                    0

      countries_shipped_to  origin_country  \
56                      40             NaN
180                     38             NaN
498                     40             NaN
507                     40             NaN
547                     40             NaN
802                     38             NaN
921                     40             NaN
943                     40             NaN
1059                    38             NaN
1147                    40             NaN
1229                    38             NaN
1244                    40             NaN
1256                    38             NaN
1289                    40             NaN
1296                    40             NaN

                                          product_url
56    https://www.wish.com/c/5e81acbde187530740f207c6
180   https://www.wish.com/c/5dde07c651fe4539f9c3ee70
498   https://www.wish.com/c/552f840fcea30816e52aabcf
507   https://www.wish.com/c/5d8d8f2e0c400f2f97671e30
547   https://www.wish.com/c/56f640b461d6cf68cb5c5d83
802   https://www.wish.com/c/5d82f19340367911da1b9ee7
921   https://www.wish.com/c/5dafd1e7e580730831a8a64c
943   https://www.wish.com/c/57ccc65975aea72c65411bc6
1059  https://www.wish.com/c/5d3120c92435742c362a09ec
1147  https://www.wish.com/c/5d8d8f2e0c400f2f97671e30
1229  https://www.wish.com/c/5d82f19340367911da1b9ee7
1244  https://www.wish.com/c/5d806bcf77593b45bd7cff78
1256  https://www.wish.com/c/5d3eba3f20e552131d7dcb40
1289  https://www.wish.com/c/5e81acbde187530740f207c6
1296  https://www.wish.com/c/5801bf9ef22bef78458987d8

[15 rows x 24 columns]

In [18]:
df['origin_country'].fillna('CN',inplace=True)
df.loc[56]

product_id                                               5e81acbde187530740f207c6
merchant_id                                              5268759b736046671957190c
merchant_title                                                          Maryswill
merchant_rating_count                                                       91631
merchant_rating                                                          3.837937
title_orig                      New Fashion Summer Women Casual Dress Round Ne...
rating_count                                                                   52
rating                                                                       3.56
uses_ad_boosts                                                                  0
product_variation_inventory                                                     2
merchant_has_profile_picture                                                    1
badges_count                                                                    0
badge_local_product                                                             0
badge_product_quality                                                           0
badge_fast_shipping                                                             0
tags                            Summer,Fashion,Necks,Beach,Dress,Loose,beach d...
price                                                                         1.0
retail_price                                                                   10
units_sold                                                                    100
shipping_option_price                                                           1
shipping_is_express                                                             0
countries_shipped_to                                                           40
origin_country                                                                 CN
product_url                       https://www.wish.com/c/5e81acbde187530740f207c6
Name: 56, dtype: object

In [19]:
df['income'] = df['price']*df['units_sold']
df.head(3)

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,tags,price,retail_price,units_sold,shipping_option_price,shipping_is_express,countries_shipped_to,origin_country,product_url,income
0,5e9ae51d43d6a96e303acdb0,595097d6a26f6e070cb878d1,zgrdejia,568,4.128521,2020 Summer Vintage Flamingo Print Pajamas Se...,54,3.76,0,50,...,"Summer,Fashion,womenunderwearsuit,printedpajam...",16.0,14,100,4,0,34,CN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,1600.0
1,58940d436a0d3d5da4e95a38,56458aa03a698c35c9050988,SaraHouse,17752,3.899673,Women's Casual Summer Sleeveless Sexy Mini Dress,6135,3.45,1,50,...,"Mini,womens dresses,Summer,Patchwork,fashion d...",8.0,22,20000,2,0,41,CN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,160000.0
3,5cedf17ad1d44c52c59e4aca,58cfdefdacb37b556efdff7c,allenfan,23832,4.020435,Hot Summer Cool T Shirt for Women Fashion Tops...,579,4.03,1,50,...,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",8.0,8,5000,2,0,41,CN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,40000.0

In [20]:
df['income'].describe()

count      1184.000000
mean      46577.752534
std       80563.483558
min         100.000000
25%        3847.500000
50%       12000.000000
75%       60000.000000
max      800000.000000
Name: income, dtype: float64

In [21]:
def Get_Income_Cat(income):
    if income <= 3847.5:
        return 'Low income'
    elif income <= 12000.0:
        return 'Medium income'
    elif income <= 60000.0:
        return 'High income'
    else:
        return 'Great income'
print(Get_Income_Cat(79999))

Great income

In [22]:
print(Get_Income_Cat(11999))

Medium income

In [23]:
df['IncomeCat']=df['income'].apply(Get_Income_Cat)
df.head(3)

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,price,retail_price,units_sold,shipping_option_price,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat
0,5e9ae51d43d6a96e303acdb0,595097d6a26f6e070cb878d1,zgrdejia,568,4.128521,2020 Summer Vintage Flamingo Print Pajamas Se...,54,3.76,0,50,...,16.0,14,100,4,0,34,CN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,1600.0,Low income
1,58940d436a0d3d5da4e95a38,56458aa03a698c35c9050988,SaraHouse,17752,3.899673,Women's Casual Summer Sleeveless Sexy Mini Dress,6135,3.45,1,50,...,8.0,22,20000,2,0,41,CN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,160000.0,Great income
3,5cedf17ad1d44c52c59e4aca,58cfdefdacb37b556efdff7c,allenfan,23832,4.020435,Hot Summer Cool T Shirt for Women Fashion Tops...,579,4.03,1,50,...,8.0,8,5000,2,0,41,CN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,40000.0,High income

In [24]:
df['countries_shipped_to'].describe()

count    1184.000000
mean       40.820101
std        19.668871
min         6.000000
25%        32.000000
50%        40.000000
75%        43.000000
max       139.000000
Name: countries_shipped_to, dtype: float64

In [25]:
def Get_CoShip_Cat(coship):
    if coship <= 32:
        return '32 countries or lower'
    elif coship <= 40:
        return 'Between 33 and 40 countries'
    elif coship <= 43:
        return 'Between 41 and 43 countries'
    else:
        return '44 countries or higher'
print(Get_CoShip_Cat(125))

44 countries or higher

In [26]:
print(Get_CoShip_Cat(38))

Between 33 and 40 countries

In [27]:
df['coship_cat']=df['countries_shipped_to'].apply(Get_CoShip_Cat)
df.tail(3)

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,retail_price,units_sold,shipping_option_price,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat,coship_cat
1568,5d5fadc99febd9356cbc52ee,5b507899ab577736508a0782,cxuelin99126,5316,4.224605,New Fashion Women Bohemia Dandelion Print Tee ...,1367,4.08,1,50,...,9,10000,2,0,41,CN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,60000.0,High income,Between 41 and 43 countries
1569,5eccd22b4497b86fd48f16b4,54d83b6b6b8a771e478558de,sell best quality goods,4435,3.696054,10 Color Women Summer Shorts Lace Up Elastic W...,28,3.07,1,2,...,56,100,1,0,26,CN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,200.0,Low income,32 countries or lower
1570,5e74be96034d613d42b52dfe,5b42da1bf64320209fc8da69,shixueying,210,3.961905,New Men Siwmwear Beach-Shorts Men Summer Quick...,59,3.71,0,15,...,19,100,2,0,11,CN,https://www.wish.com/c/5e74be96034d613d42b52dfe,500.0,Low income,32 countries or lower

In [28]:
def Get_MeRating_Cat(mrate):
    if mrate <= 2:
        return 'Low Rating'
    elif mrate <= 3:
        return 'Medium Rating'
    elif mrate <= 4:
        return 'High Rating'
    else:
        return 'Great Rating'
print(Get_MeRating_Cat(3.5))

High Rating

In [29]:
df['MeRating_Cat']=df['merchant_rating'].apply(Get_MeRating_Cat)
df.tail(3)

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,units_sold,shipping_option_price,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat,coship_cat,MeRating_Cat
1568,5d5fadc99febd9356cbc52ee,5b507899ab577736508a0782,cxuelin99126,5316,4.224605,New Fashion Women Bohemia Dandelion Print Tee ...,1367,4.08,1,50,...,10000,2,0,41,CN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,60000.0,High income,Between 41 and 43 countries,Great Rating
1569,5eccd22b4497b86fd48f16b4,54d83b6b6b8a771e478558de,sell best quality goods,4435,3.696054,10 Color Women Summer Shorts Lace Up Elastic W...,28,3.07,1,2,...,100,1,0,26,CN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,200.0,Low income,32 countries or lower,High Rating
1570,5e74be96034d613d42b52dfe,5b42da1bf64320209fc8da69,shixueying,210,3.961905,New Men Siwmwear Beach-Shorts Men Summer Quick...,59,3.71,0,15,...,100,2,0,11,CN,https://www.wish.com/c/5e74be96034d613d42b52dfe,500.0,Low income,32 countries or lower,High Rating

In [30]:
df['Rating_Cat']=df['rating'].apply(Get_MeRating_Cat)
df.tail(3)

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,shipping_option_price,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat,coship_cat,MeRating_Cat,Rating_Cat
1568,5d5fadc99febd9356cbc52ee,5b507899ab577736508a0782,cxuelin99126,5316,4.224605,New Fashion Women Bohemia Dandelion Print Tee ...,1367,4.08,1,50,...,2,0,41,CN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,60000.0,High income,Between 41 and 43 countries,Great Rating,Great Rating
1569,5eccd22b4497b86fd48f16b4,54d83b6b6b8a771e478558de,sell best quality goods,4435,3.696054,10 Color Women Summer Shorts Lace Up Elastic W...,28,3.07,1,2,...,1,0,26,CN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,200.0,Low income,32 countries or lower,High Rating,High Rating
1570,5e74be96034d613d42b52dfe,5b42da1bf64320209fc8da69,shixueying,210,3.961905,New Men Siwmwear Beach-Shorts Men Summer Quick...,59,3.71,0,15,...,2,0,11,CN,https://www.wish.com/c/5e74be96034d613d42b52dfe,500.0,Low income,32 countries or lower,High Rating,High Rating

In [31]:
df['price_difference']=df['retail_price']-df['price']
df.head(3)

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat,coship_cat,MeRating_Cat,Rating_Cat,price_difference
0,5e9ae51d43d6a96e303acdb0,595097d6a26f6e070cb878d1,zgrdejia,568,4.128521,2020 Summer Vintage Flamingo Print Pajamas Se...,54,3.76,0,50,...,0,34,CN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,1600.0,Low income,Between 33 and 40 countries,Great Rating,High Rating,-2.0
1,58940d436a0d3d5da4e95a38,56458aa03a698c35c9050988,SaraHouse,17752,3.899673,Women's Casual Summer Sleeveless Sexy Mini Dress,6135,3.45,1,50,...,0,41,CN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,160000.0,Great income,Between 41 and 43 countries,High Rating,High Rating,14.0
3,5cedf17ad1d44c52c59e4aca,58cfdefdacb37b556efdff7c,allenfan,23832,4.020435,Hot Summer Cool T Shirt for Women Fashion Tops...,579,4.03,1,50,...,0,41,CN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,40000.0,High income,Between 41 and 43 countries,Great Rating,Great Rating,0.0

In [46]:
import openpyxl
from openpyxl.utils.dataframe import dataframe_to_rows

In [47]:
wb=openpyxl.Workbook()

In [48]:
ws=wb.active

In [49]:
ws.title='Backup full data'

In [50]:
headers = tuple(df.keys())
ws.append (headers)
number_of_rows = df.shape[0]
for row  in range (number_of_rows):
    ws.append(tuple (df.iloc[row]))

In [51]:
ws.sheet_properties.tabColor='000000'

In [53]:
wb.save('Backup_Final.xlsx')

In [39]:
import seaborn as sns

In [40]:
corr_mtx=df[['merchant_rating_count','merchant_rating','rating_count','rating','uses_ad_boosts','product_variation_inventory','merchant_has_profile_picture','price','retail_price','units_sold','shipping_option_price','countries_shipped_to','income','price_difference']].corr()
corr_mtx

,merchant_rating_count,merchant_rating,rating_count,rating,uses_ad_boosts,product_variation_inventory,merchant_has_profile_picture,price,retail_price,units_sold,shipping_option_price,countries_shipped_to,income,price_difference
merchant_rating_count,1.000000,0.127585,0.246136,0.046062,0.018250,0.066443,0.096878,-0.036759,0.035368,0.261325,-0.052645,0.128579,0.229723,0.040970
merchant_rating,0.127585,1.000000,0.128843,0.340375,-0.055275,0.122360,0.074249,0.026270,0.079164,0.101043,0.015369,0.094778,0.122588,0.078608
rating_count,0.246136,0.128843,1.000000,0.102455,-0.051917,0.102804,0.146566,-0.033091,0.048244,0.892352,-0.036178,-0.012035,0.822229,0.053829
rating,0.046062,0.340375,0.102455,1.000000,-0.036498,0.122195,0.039221,0.050605,0.060647,0.076853,0.064646,0.026742,0.083472,0.056543
uses_ad_boosts,0.018250,-0.055275,-0.051917,-0.036498,1.000000,-0.167632,-0.027137,-0.070082,-0.032313,-0.019183,-0.041424,-0.026612,-0.013229,-0.024924
product_variation_inventory,0.066443,0.122360,0.102804,0.122195,-0.167632,1.000000,-0.007989,0.265149,0.129753,0.101087,0.237865,0.101300,0.132071,0.102046
merchant_has_profile_picture,0.096878,0.074249,0.146566,0.039221,-0.027137,-0.007989,1.000000,0.016170,0.038295,0.132592,0.021444,0.000337,0.150776,0.037608
price,-0.036759,0.026270,-0.033091,0.050605,-0.070082,0.265149,0.016170,1.000000,0.327593,-0.062768,0.854289,-0.022189,0.142549,0.217755
retail_price,0.035368,0.079164,0.048244,0.060647,-0.032313,0.129753,0.038295,0.327593,1.000000,0.000606,0.281422,0.051171,0.069370,0.993482
units_sold,0.261325,0.101043,0.892352,0.076853,-0.019183,0.101087,0.132592,-0.062768,0.000606,1.000000,-0.068482,-0.026759,0.907154,0.008200
shipping_option_price,-0.052645,0.015369,-0.036178,0.064646,-0.041424,0.237865,0.021444,0.854289,0.281422,-0.068482,1.000000,-0.051755,0.115610,0.187640
countries_shipped_to,0.128579,0.094778,-0.012035,0.026742,-0.026612,0.101300,0.000337,-0.022189,0.051171,-0.026759,-0.051755,1.000000,-0.043532,0.055538
income,0.229723,0.122588,0.822229,0.083472,-0.013229,0.132071,0.150776,0.142549,0.069370,0.907154,0.115610,-0.043532,1.000000,0.054461
price_difference,0.040970,0.078608,0.053829,0.056543,-0.024924,0.102046,0.037608,0.217755,0.993482,0.008200,0.187640,0.055538,0.054461,1.000000

In [41]:
df['product_variation_inventory'].describe()

count    1184.000000
mean       35.559966
std        20.467812
min         1.000000
25%        10.000000
50%        50.000000
75%        50.000000
max        50.000000
Name: product_variation_inventory, dtype: float64

In [42]:
df['merchant_rating_count'].describe()

count    1.184000e+03
mean     3.099064e+04
std      8.844324e+04
min      2.100000e+01
25%      3.646750e+03
50%      9.932000e+03
75%      3.095350e+04
max      2.174765e+06
Name: merchant_rating_count, dtype: float64

In [44]:
df['units_sold'].describe()

count      1184.000000
mean       5735.979730
std       10412.957143
min         100.000000
25%        1000.000000
50%        1000.000000
75%       10000.000000
max      100000.000000
Name: units_sold, dtype: float64

In [45]:
df['price_difference'].describe()

count    1184.000000
mean       15.572998
std        30.384110
min        -3.000000
25%        -1.000000
50%         0.135000
75%        18.000000
max       244.000000
Name: price_difference, dtype: float64

In [55]:
df.loc[df['product_id'] == '54bdf18039b8c045f118936a']

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat,coship_cat,MeRating_Cat,Rating_Cat,price_difference
214,54bdf18039b8c045f118936a,5417aada4ad3ab27e954b76c,"SHENZHEN LONGDRAGON TECHNOLOGY CO.,LTD",108048,4.052504,New Aeeival Women Clothing Long Sleeve Autumn ...,11062,3.76,1,10,...,0,38,CN,https://www.wish.com/c/54bdf18039b8c045f118936a,800000.0,Great income,Between 33 and 40 countries,Great Rating,High Rating,-1.0

In [56]:
df.loc[df['merchant_id'] == '53a2a09ad91139519161a267']

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat,coship_cat,MeRating_Cat,Rating_Cat,price_difference
353,56a88f23e726b165ec424c94,53a2a09ad91139519161a267,FashionForChanny,165915,4.256077,Women Lace Floral White Long Maxi Dress Boho C...,4266,4.29,1,50,...,0,38,CN,https://www.wish.com/c/56a88f23e726b165ec424c94,240000.0,Great income,Between 33 and 40 countries,Great Rating,Great Rating,106.0
401,563707b0e5be09157176fe80,53a2a09ad91139519161a267,FashionForChanny,165915,4.256077,Women Lace Beach Boho Maxi Sundress Sleeveless...,6735,3.94,1,2,...,0,38,CN,https://www.wish.com/c/563707b0e5be09157176fe80,750000.0,Great income,Between 33 and 40 countries,Great Rating,High Rating,100.0
600,5a98b8cd414de27e9ef44d4a,53a2a09ad91139519161a267,FashionForChanny,165915,4.256077,2018 New ZANZEA Beach Romper Women Jumpsuits F...,1020,3.97,1,50,...,0,38,CN,https://www.wish.com/c/5a98b8cd414de27e9ef44d4a,65000.0,Great income,Between 33 and 40 countries,Great Rating,High Rating,55.0

In [58]:
df.isna().sum()

product_id                      0
merchant_id                     0
merchant_title                  0
merchant_rating_count           0
merchant_rating                 0
title_orig                      0
rating_count                    0
rating                          0
uses_ad_boosts                  0
product_variation_inventory     0
merchant_has_profile_picture    0
badges_count                    0
badge_local_product             0
badge_product_quality           0
badge_fast_shipping             0
tags                            0
price                           0
retail_price                    0
units_sold                      0
shipping_option_price           0
shipping_is_express             0
countries_shipped_to            0
origin_country                  0
product_url                     0
income                          0
IncomeCat                       0
coship_cat                      0
MeRating_Cat                    0
Rating_Cat                      0
price_difference                0
dtype: int64

In [60]:
df.loc[df['product_id'] == '5d1c260af02c727e3c3d0c61']

,product_id,merchant_id,merchant_title,merchant_rating_count,merchant_rating,title_orig,rating_count,rating,uses_ad_boosts,product_variation_inventory,...,shipping_is_express,countries_shipped_to,origin_country,product_url,income,IncomeCat,coship_cat,MeRating_Cat,Rating_Cat,price_difference
956,5d1c260af02c727e3c3d0c61,559f372b577ce1196ef7f66c,"shenzhen dcr technology co.,ltd",1032,4.577519,2019 Summer Women Newest Transparent Sheer Thi...,110,4.33,1,50,...,0,43,CN,https://www.wish.com/c/5d1c260af02c727e3c3d0c61,800.0,Low income,Between 41 and 43 countries,Great Rating,Great Rating,39.0